services:
  mongo:
    image: mongo:8.0 
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on the default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Set the admin username
      MONGO_INITDB_ROOT_PASSWORD: password # Set the admin password
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
      - mongo-config:/data/configdb # Persist MongoDB configuration
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app  # Bind source code for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local